/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.Scanner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class FramePesan extends javax.swing.JFrame {
public String barang;
public String harga;

    /**
     * Creates new form FramePesan
     */
    public FramePesan() {
        initComponents();
         setExtendedState(Frame.MAXIMIZED_BOTH);
         this.showtables(this);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bakso = new javax.swing.JCheckBox();
        ayamgeprek = new javax.swing.JCheckBox();
        ketoprak = new javax.swing.JCheckBox();
        sotoayam = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fanta = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        teh = new javax.swing.JCheckBox();
        cola = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        air = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fruit = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel1.setText("                              M E N U");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 860, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/geprek.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 170, 90, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/ket.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 300, 90, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/soto.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 470, 110, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/bakso.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 630, 110, 90);

        bakso.setText("Bakso");
        bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baksoActionPerformed(evt);
            }
        });
        jPanel1.add(bakso);
        bakso.setBounds(130, 650, 100, 30);

        ayamgeprek.setBackground(new java.awt.Color(255, 255, 255));
        ayamgeprek.setText("Ayam Geprek");
        ayamgeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamgeprekActionPerformed(evt);
            }
        });
        jPanel1.add(ayamgeprek);
        ayamgeprek.setBounds(150, 210, 100, 30);

        ketoprak.setText("Ketoprak");
        ketoprak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketoprakActionPerformed(evt);
            }
        });
        jPanel1.add(ketoprak);
        ketoprak.setBounds(120, 340, 100, 30);

        sotoayam.setText("Soto Ayam");
        sotoayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoayamActionPerformed(evt);
            }
        });
        jPanel1.add(sotoayam);
        sotoayam.setBounds(140, 490, 100, 30);

        jLabel6.setText("Rp. 15.000");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 650, 90, 30);

        jLabel7.setText("Rp. 12.000");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 210, 90, 30);

        jLabel8.setText("Rp. 14.000");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 340, 90, 30);

        jLabel9.setText("Rp. 15.000");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 490, 90, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/aq.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 200, 50, 120);

        fanta.setText("Fanta");
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });
        jPanel1.add(fanta);
        fanta.setBounds(430, 600, 90, 30);

        jLabel11.setText("Rp.5.000");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(620, 640, 70, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/coca.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 390, 70, 130);

        teh.setText("Teh Botol");
        jPanel1.add(teh);
        teh.setBounds(620, 610, 90, 30);

        cola.setText("Coca-Cola");
        cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaActionPerformed(evt);
            }
        });
        jPanel1.add(cola);
        cola.setBounds(440, 420, 90, 30);

        jLabel13.setText("Rp.4.000");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 250, 70, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/fan.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(380, 570, 50, 130);

        jLabel15.setText("Rp.5.000");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(450, 450, 70, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/fru.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(550, 390, 50, 110);

        air.setText("Air Mineral");
        air.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airActionPerformed(evt);
            }
        });
        jPanel1.add(air);
        air.setBounds(520, 210, 90, 30);

        jLabel17.setText("Rp.5.000");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(440, 640, 70, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/teh.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(550, 560, 60, 150);

        fruit.setText("Fruit Tea");
        jPanel1.add(fruit);
        fruit.setBounds(600, 400, 90, 30);

        jLabel19.setText("Rp.5.000");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(610, 440, 70, 30);

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/che.jpg"))); // NOI18N
        jLabel21.setText("Selamat Menikmati");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(810, 550, 440, 180);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Cetak Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1090, 470, 100, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(530, 280, 50, 40);

        jTextField2.setText("  ");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(200, 240, 50, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 380, 50, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(220, 530, 50, 40);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(220, 690, 50, 40);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(440, 670, 50, 40);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(620, 670, 50, 40);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(610, 470, 50, 40);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(450, 480, 50, 40);

        reset.setBackground(new java.awt.Color(255, 51, 0));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(950, 470, 110, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "no", "nama makanan", "harga", "jumlah"
            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(700, 130, 480, 200);

        tabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelActionPerformed(evt);
            }
        });
        jPanel1.add(tabel);
        tabel.setBounds(700, 360, 480, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ketoprakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketoprakActionPerformed
        // TODO add your handling code here:
        barang="Ketoprak";
        harga="14000";
        ketoprak.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_ketoprakActionPerformed
    
    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
        // TODO add your handling code here:
        barang="Fanta";
        harga="14000";
        fanta.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_fantaActionPerformed

    private void colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaActionPerformed
        // TODO add your handling code here:
        barang="Coca-cola";
        harga="14000";
        cola.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_colaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*try{
        MessageFormat header = new MessageFormat("BKL Kantin");
        MessageFormat header = new MessageFormat("Page(0,number,integer");
        jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }catch (java.awt.print.PrinterException e){
            System.err.format("Tidak Bisa print %s%n", e.getMessage());
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ayamgeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamgeprekActionPerformed
        // TODO add your handling code here:
        barang="Ayam Geprek";
        harga="14000";
        ayamgeprek.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_ayamgeprekActionPerformed

    private void sotoayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoayamActionPerformed
        // TODO add your handling code here:
        barang="Soto Ayam";
        harga="14000";
        sotoayam.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_sotoayamActionPerformed

    private void baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baksoActionPerformed
        // TODO add your handling code here:
        barang="Bakso";
        harga="14000";
        bakso.setSelected(true);
        tabel.setText(String.format(barang, tabel));
        tabel.setText(String.valueOf(harga));
    }//GEN-LAST:event_baksoActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        new selamatdatang().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_resetActionPerformed
public void showtables(FramePesan Fr) {
             int i=0;
             
            
            Object [] rows={"No","Nama Makanan","Harga"};
            DefaultTableModel dtm=new DefaultTableModel(null,rows){
               public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
               }
            };
          
           
            Fr.jTable1.setModel(dtm);
            Fr.jTable1.setBorder(null);
            Fr.jTable1.removeAll();
             String query="select * from makanan;";
        
        
        try{
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/kantin_bkl","root","");
            Statement stat = koneksi.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            
            while(hasil.next()){
                Object[] obj=new Object[3];
               
                obj[0]=hasil.getString("kode_makanan");
                obj[1]=hasil.getString("nama_makanan");
                obj[2]=hasil.getString("harga_makanan");
//                int flag=hasil.getInt("flag");               
                
//                mapPegawai.put(i,obj[0]);
                i++;
                
//                if(flag!=0){
                dtm.addRow(obj);
             }
        }
        catch (SQLException e){
            System.out.println("Gagal eksekusi query select");
        }
    }
    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1PropertyChange

    private void tabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelActionPerformed

    private void airActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox air;
    private javax.swing.JCheckBox ayamgeprek;
    private javax.swing.JCheckBox bakso;
    private javax.swing.JCheckBox cola;
    private javax.swing.JCheckBox fanta;
    private javax.swing.JCheckBox fruit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JCheckBox ketoprak;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox sotoayam;
    private javax.swing.JTextField tabel;
    private javax.swing.JCheckBox teh;
    // End of variables declaration//GEN-END:variables
}
